node{
	def app

	stage ('Clone'){
		checkout scm	
	}

	stage('Build image'){
		app = docker.build("dashboard/back-test-jenkins","-f back/Dockerfile")
	}

//	stage('Run image'){
//		docker.image('dashboard/back-test-jenkins').withRun('-p 8082:80'){c ->
//		sh 'docker ps'
//
//		sh 'curl localhost:8082'
//	}	
	
//	}


}
