pipeline {
  agent any
  tools {
    maven 'M3'
  }
  stages {
    stage('Build image') {
      steps {
        	sh  'cd back/ && mvn package'
		sh 'mkdir -p back/target/dependency'
	      	sh 'cd back/target/dependency && jar -xf ../*jar'
	      	sh 'docker ps -al'
		
	      	sh 'docker build -t dashboard/back-test-jenkins back/.'

      }
    }
  }
}
