node{
	def app

	stage ('Clone'){
		checkout scm	
	}

	stage('Build image'){
		app = docker.build("dashboard/front-test-jenkins","-f front/Dockerfile")
	}

//	stage('Run image'){
//		docker.image('dashboard/front-test-jenkins').withRun('-p 8081:80'){c ->
//		sh 'docker ps'
//
//		sh 'curl localhost:8081'
//	}	
	
//	}


}
